version: '3.7'

services:
  web:
    # php 8.0.10
    image: stonedz/docker-php-dev
    container_name: web
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=localhost
      - DOCUMENT_ROOT=/public
    volumes:
      # development directory
      - ./html/:/var/www/html/public
      # expose apache logs to host
      - ./log/:/var/log/apache2/
      # expose apache2 and php config to host
      - ./etc/:/docker/etc/
      # expose ssl certificates to host
      - ./ssl/:/etc/ssl/apache2/
